// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Change
{
    float deltaHeight;
    int owner;
};

RWStructuredBuffer<Change> Changes;

int Resolution;
RWStructuredBuffer<float> Heights;
RWStructuredBuffer<int> Ids;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = (int)(id.x * Resolution + id.y);
    Heights[index] += Changes[index].deltaHeight;
    Ids[index] = Changes[index].owner;
}
